package com.businessalliance.hibernate;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Favproduc generated by MyEclipse Persistence Tools
 */

public class Favproduct implements java.io.Serializable {

	// Fields

	private Long id;

	private String title;

	private Double price;

	private Integer funfirst;

	private Integer funsecond;

	private Integer funthird;

	private Integer funfour;

	private String sellername;

	private Long userid;

	private String producturl;

	private String auctionid;
	
	private Boolean serverexist;

	// Constructors

	public Boolean getServerexist() {
		return serverexist;
	}

	public void setServerexist(Boolean serverexist) {
		this.serverexist = serverexist;
	}


	// Constructors

	/** default constructor */
	public Favproduct() {
	}


	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		title= title.replace("'", "''");
		this.title = title.replace("\\", "\\\\");
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Integer getFunfirst() {
		return this.funfirst;
	}

	public void setFunfirst(Integer funfirst) {
		this.funfirst = funfirst;
	}

	public Integer getFunsecond() {
		return this.funsecond;
	}

	public void setFunsecond(Integer funsecond) {
		this.funsecond = funsecond;
	}

	public Integer getFunthird() {
		return this.funthird;
	}

	public void setFunthird(Integer funthird) {
		this.funthird = funthird;
	}

	public Integer getFunfour() {
		return this.funfour;
	}

	public void setFunfour(Integer funfour) {
		this.funfour = funfour;
	}

	public String getSellername() {
		return this.sellername;
	}

	public void setSellername(String sellername) {
		this.sellername = sellername;
	}

	

	public Long getUserid() {
		return userid;
	}

	public void setUserid(Long userid) {
		this.userid = userid;
	}

	public String getProducturl() {
		return this.producturl;
	}

	public void setProducturl(String producturl) {
		this.producturl = producturl;
	}

	public String getAuctionid() {
		return this.auctionid;
	}

	public void setAuctionid(String auctionid) {
		this.auctionid = auctionid;
	}

}