package com.businessalliance.hibernate;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Favshop generated by MyEclipse Persistence Tools
 */

public class Favshop implements java.io.Serializable {

	// Fields

	private Long id;

	private String sellername;

	private Long saveuserId;

	
	private Boolean serverexist;

	// Constructors

	public Boolean getServerexist() {
		return serverexist;
	}

	public void setServerexist(Boolean serverexist) {
		this.serverexist = serverexist;
	}


	// Constructors

	/** default constructor */
	public Favshop() {
	}



	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getSellername() {
		return this.sellername;
	}

	public void setSellername(String sellername) {
		this.sellername = sellername;
	}


	public Long getSaveuserId() {
		return saveuserId;
	}

	public void setSaveuserId(Long saveuserId) {
		this.saveuserId = saveuserId;
	}

}