package com.businessalliance.hibernate;

import java.util.Date;

/**
 * Userinfo generated by MyEclipse Persistence Tools
 */

public class Mission implements java.io.Serializable {

	// Fields

	private Long id;

	private String province;
	
	private String city;

	private String taobaohref;

	private String shopname;

	private Boolean iscompaney;

	private String salerate;

	private String salesixrecent;

	private String salesixpre;

	private String buyrate;

	private String buysixrecent;

	private String buysixpre;

	private String username;

	private String companeyname;

	private String personspace;

	private Integer salelevel;
	
	private Integer buylevel;
	

	private Boolean mission;

	private String lastchecktime;


	// Constructors

	public String getLastchecktime() {
		return lastchecktime;
	}

	public void setLastchecktime(String lastchecktime) {
		this.lastchecktime = lastchecktime;
	}

	public Boolean getMission() {
		return mission;
	}

	public void setMission(Boolean mission) {
		this.mission = mission;
	}

	/** default constructor */
	public Mission() {
	}

	

	// Property accessors

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public String getTaobaohref() {
		return this.taobaohref;
	}

	public void setTaobaohref(String taobaohref) {
		this.taobaohref = taobaohref;
	}

	public String getShopname() {
		return this.shopname;
	}

	public void setShopname(String shopname) {
		this.shopname = shopname;
	}

	public Boolean getIscompaney() {
		return this.iscompaney;
	}

	public void setIscompaney(Boolean iscompaney) {
		this.iscompaney = iscompaney;
	}

	public String getSalerate() {
		return this.salerate;
	}

	public void setSalerate(String salerate) {
		this.salerate = salerate;
	}

	public String getSalesixrecent() {
		return this.salesixrecent;
	}

	public void setSalesixrecent(String salesixrecent) {
		this.salesixrecent = salesixrecent;
	}

	public String getSalesixpre() {
		return this.salesixpre;
	}

	public void setSalesixpre(String salesixpre) {
		this.salesixpre = salesixpre;
	}

	public String getBuyrate() {
		return this.buyrate;
	}

	public void setBuyrate(String buyrate) {
		this.buyrate = buyrate;
	}

	public String getBuysixrecent() {
		return this.buysixrecent;
	}

	public void setBuysixrecent(String buysixrecent) {
		this.buysixrecent = buysixrecent;
	}

	public String getBuysixpre() {
		return this.buysixpre;
	}

	public void setBuysixpre(String buysixpre) {
		this.buysixpre = buysixpre;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getCompaneyname() {
		return this.companeyname;
	}

	public void setCompaneyname(String companeyname) {
		this.companeyname = companeyname;
	}

	public String getPersonspace() {
		return this.personspace;
	}

	public void setPersonspace(String personspace) {
		this.personspace = personspace;
	}

	public Integer getSalelevel() {
		return this.salelevel;
	}

	public void setSalelevel(Integer salelevel) {
		this.salelevel = salelevel;
	}	
	
	public Integer getBuylevel() {
		return buylevel;
	}

	public void setBuylevel(Integer buylevel) {
		this.buylevel = buylevel;
	}	
	
}