package com.businessalliance.hibernate;

/**
 * Procatfour generated by MyEclipse Persistence Tools
 */

public class Procatfour implements java.io.Serializable {

	// Fields

	private Long id;

	private Procatthird procatthird;

	private String categoryname;

	// Constructors

	/** default constructor */
	public Procatfour() {
	}

	/** minimal constructor */
	public Procatfour(Procatthird procatthird) {
		this.procatthird = procatthird;
	}

	/** full constructor */
	public Procatfour(Procatthird procatthird, String categoryname) {
		this.procatthird = procatthird;
		this.categoryname = categoryname;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Procatthird getProcatthird() {
		return this.procatthird;
	}

	public void setProcatthird(Procatthird procatthird) {
		this.procatthird = procatthird;
	}

	public String getCategoryname() {
		return this.categoryname;
	}

	public void setCategoryname(String categoryname) {
		this.categoryname = categoryname;
	}

}