package com.businessalliance.hibernate;

import java.util.HashSet;
import java.util.Set;

/**
 * Procatthird generated by MyEclipse Persistence Tools
 */

public class Procatthird implements java.io.Serializable {

	// Fields

	private Long id;

	private Procatsecond procatsecond;

	private String categoryname;

	private Set procatfours = new HashSet(0);

	// Constructors

	/** default constructor */
	public Procatthird() {
	}

	/** minimal constructor */
	public Procatthird(Procatsecond procatsecond) {
		this.procatsecond = procatsecond;
	}

	/** full constructor */
	public Procatthird(Procatsecond procatsecond, String categoryname,
			Set procatfours) {
		this.procatsecond = procatsecond;
		this.categoryname = categoryname;
		this.procatfours = procatfours;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Procatsecond getProcatsecond() {
		return this.procatsecond;
	}

	public void setProcatsecond(Procatsecond procatsecond) {
		this.procatsecond = procatsecond;
	}

	public String getCategoryname() {
		return this.categoryname;
	}

	public void setCategoryname(String categoryname) {
		this.categoryname = categoryname;
	}

	public Set getProcatfours() {
		return this.procatfours;
	}

	public void setProcatfours(Set procatfours) {
		this.procatfours = procatfours;
	}

}