package com.businessalliance.hibernate;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Product generated by MyEclipse Persistence Tools
 */

public class Product implements java.io.Serializable {

	// Fields

	private Long id;

	private String title;

	private Double price;

	private Integer funfirst;

	private Integer funsecond;

	private Integer funthird;

	private Integer funfour;

	private String username;

	private String productUrl;

	private String auctionid;

	private Date addDay;
	
	
	private Boolean serverexist;

	public Boolean getServerexist() {
		return serverexist;
	}

	public void setServerexist(Boolean serverexist) {
		this.serverexist = serverexist;
	}

	// Constructors

	/** default constructor */
	public Product() {
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		title= title.replace("'", "''");
		this.title = title.replace("\\", "\\\\");
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}
	
	public Integer getFunfirst() {
		return funfirst;
	}

	public void setFunfirst(Integer funfirst) {
		this.funfirst = funfirst;
	}

	public Integer getFunfour() {
		return funfour;
	}

	public void setFunfour(Integer funfour) {
		this.funfour = funfour;
	}

	public Integer getFunsecond() {
		return funsecond;
	}

	public void setFunsecond(Integer funsecond) {
		this.funsecond = funsecond;
	}

	public Integer getFunthird() {
		return funthird;
	}

	public void setFunthird(Integer funthird) {
		this.funthird = funthird;
	}


	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getProductUrl() {
		return this.productUrl;
	}

	public void setProductUrl(String productUrl) {
		this.productUrl = productUrl;
	}

	public String getAuctionid() {
		return auctionid;
	}

	public void setAuctionid(String auctionid) {
		this.auctionid = auctionid;
	}

	public Date getAddDay() {
		return this.addDay;
	}

	public void setAddDay(Date addDay) {
		this.addDay = addDay;
	}
	
}